Update zh_CN.lang
LWHK/Thaumic-Wands pull request #2
Opened 2020-08-12 07:04 UTC by TUsama

2020-08-12 07:58 UTC, Dawnwalker666 requested changes

2020-08-12 07:58 UTC, Dawnwalker666 commented on src/main/resources/assets/thaumicwands/lang/zh_CN.lang
> +research.CAP_ALKIMIUM.stage.1=由于它仅是黄铜的一种派生金属，所以我最初其实并没有对它抱有太高的期望。然而我没料到，它居然能和多种要素产生协同。 <br> 它不仅有着 5% 的灵气减免，还有着 1 的 §3水§r，§2大地§r以及§7秩序§r水晶消耗减免，真是妙极了。
魔力水晶碎片的要素拉丁名不要翻译。但是要严格区分魔力水晶碎片与要素结晶的区别。毕竟有刚玩神秘的玩家，译名保持标准化和一致性比较好。
![11](https://user-images.githubusercontent.com/49862610/89990119-7a29b880-dcb4-11ea-871f-81d79e9004f2.png)
![12](https://user-images.githubusercontent.com/49862610/89990130-7d24a900-dcb4-11ea-8095-ba6bd566e003.png)

2020-08-17 03:29 UTC, Determancer commented on src/main/resources/assets/thaumicwands/lang/zh_CN.lang
> +research.CAP_ALKIMIUM.stage.0=从我发现了炼化金属之后，它就替代了黄铜的工作角色，我开始大量替换掉黄铜，换上这一种新的金属。现在，该给我的黄铜杖端换一换了。
扩写偏多，缩一下。
```suggestion
research.CAP_ALKIMIUM.stage.0=从我发现了炼化金属之后，我就开始大量地使用它来替换黄铜。现在，也该用它给我的黄铜杖端换一换了。
```

2020-08-17 03:31 UTC, Determancer commented on src/main/resources/assets/thaumicwands/lang/zh_CN.lang
> +research.CAP_ALKIMIUM.stage.1=由于它仅是黄铜的一种派生金属，所以我最初其实并没有对它抱有太高的期望。然而我没料到，它居然能和多种要素产生协同。 <br> 它不仅有着 5% 的灵气减免，还有着 1 的 §3Aqua§r，§2Terra§r以及§7Ordo§r水晶消耗减免，真是妙极了。
```suggestion
research.CAP_ALKIMIUM.stage.1=由于它仅是黄铜的一种派生金属，所以我最初其实并没有对它抱有太高的期望。然而我没料到，它居然能和多种要素发生谐振。 <br> 它不仅有着 5% 的灵气减免，还有着 1 的 §3Aqua§r，§2Terra§r以及§7Ordo§r水晶消耗减免，真是妙极了。 
```

2020-08-19 15:58 UTC, Dawnwalker666 reviewed
Review完毕。没毛病。

2020-08-25 05:41 UTC, merged